# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39fb5227c034db43bafa4c8cded0021624f72870cd1251405aa8d577ce052f48f0fc65ef65ce4e3f5f6d8abccee193048d83fed8fbd24d6436e9e2c2ab147e5d

test:
  secret_key_base: 92a24321137df2911a9fdeba94483ec676a3214881127a2cc8b51ba8fe6f7d86b9cb37095f19d0c38b2e3813c8bb5eb78ee9cbdcbab648718d1a26b43dd594d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
